export const INDONESIAN_BANKS = [
  'BCA',
  'BRI',
  'BNI',
  'Bank Mandiri',
  'BSI (Bank Syariah Indonesia)',
  'BTN',
  'CIMB Niaga',
  'Bank Danamon',
  'Bank Permata',
  'Bank Mega',
  'Bank OCBC NISP',
  'Bank Panin',
  'Bank Bukopin',
  'Bank Sinarmas',
  'Bank Maybank Indonesia',
  'Bank UOB Indonesia',
  'Bank Commonwealth',
  'Bank HSBC Indonesia',
  'Bank DBS Indonesia',
  'Bank Muamalat',
  'Bank Mega Syariah',
  'BCA Syariah',
  'BNI Syariah',
  'Bank BTPN',
  'Bank Jago',
  'Bank Neo Commerce',
  'Bank Seabank Indonesia',
  'Bank Aladin Syariah',
  'Bank Raya Indonesia',
  'Bank Krom',
  'Bank DKI',
  'Bank Jatim',
  'Bank Jateng',
  'Bank Jabar Banten (BJB)',
  'Bank Sumsel Babel',
  'Bank Sumut',
  'Bank Nagari',
  'Bank Kalbar',
  'Bank Kaltimtara',
  'Bank Sulselbar',
  'Bank NTB Syariah',
  'Bank Papua',
  'Bank Aceh Syariah',
  'Bank Jasa Jakarta',
  'Gopay',
  'OVO',
  'DANA',
  'ShopeePay',
  'LinkAja',
  'Lainnya',
] as const;
